/**
 * Base esbuild configuration shared across packages.
 * Each package can import this and override specific settings as needed.
 */

export const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

/**
 * Common base configuration for all packages.
 * Override settings by spreading this config and modifying specific properties.
 */
export const baseConfig = {
	banner: {
		js: banner,
	},
	bundle: true,
	logLevel: "info",
	treeShaking: true,
	mainFields: ['module', 'main'],
	metafile: true,
};

/**
 * Helper to determine if running in production mode
 */
export const isProd = (process.argv[2] === 'production');
